trigger:
  - master
  - develop

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Npm@1
  displayName: npm ci
  inputs:
    command: 'custom'
    customCommand: 'ci'
- script: ./build.sh
- task: PublishBuildArtifacts@1
  displayName: publish build artifact itlab-front-build
  inputs:
    PathtoPublish: 'deploy'
    ArtifactName: 'itlab-front-build'